//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escola.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class escolaEntities : DbContext
    {
        public escolaEntities()
            : base("name=escolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluno> alunoes { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<pessoa> pessoas { get; set; }
        public virtual DbSet<professor> professors { get; set; }
        public virtual DbSet<aluno_materia> aluno_materia { get; set; }
    }
}
